import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { useUserProgress } from '../hooks/useUserProgress';
const Profile = () => {
    const { user } = useAuth();
    const { progress, fetchProgress, loading } = useUserProgress();
    useEffect(() => {
        fetchProgress();
    }, [fetchProgress]);
    return (_jsxs("div", { className: "max-w-2xl mx-auto", children: [_jsx("h1", { className: "text-4xl font-bold mb-8", children: "Your Profile" }), _jsxs("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 p-8 mb-6", children: [_jsx("h2", { className: "text-2xl font-bold mb-6", children: "Account Information" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "text-sm text-gray-600", children: "Email" }), _jsx("p", { className: "text-lg font-medium text-gray-900", children: user?.email || 'N/A' })] }), _jsxs("div", { children: [_jsx("label", { className: "text-sm text-gray-600", children: "User ID" }), _jsx("p", { className: "text-lg font-medium text-gray-900 font-mono text-sm", children: user?.id || 'N/A' })] })] })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-6 mb-6", children: [_jsxs("div", { className: "bg-white p-6 rounded-lg shadow-sm border border-gray-200", children: [_jsx("div", { className: "text-gray-600 text-sm font-medium", children: "Current Level" }), _jsx("div", { className: "text-4xl font-bold text-primary mt-2", children: loading ? '...' : progress?.currentLevel || 1 })] }), _jsxs("div", { className: "bg-white p-6 rounded-lg shadow-sm border border-gray-200", children: [_jsx("div", { className: "text-gray-600 text-sm font-medium", children: "Total XP" }), _jsx("div", { className: "text-4xl font-bold text-secondary mt-2", children: loading ? '...' : progress?.totalXP || 0 })] }), _jsxs("div", { className: "bg-white p-6 rounded-lg shadow-sm border border-gray-200", children: [_jsx("div", { className: "text-gray-600 text-sm font-medium", children: "Exercises Completed" }), _jsx("div", { className: "text-4xl font-bold text-accent mt-2", children: loading ? '...' : progress?.exercisesCompleted || 0 })] })] }), progress?.achievements && progress.achievements.length > 0 && (_jsxs("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 p-8", children: [_jsx("h2", { className: "text-2xl font-bold mb-4", children: "Achievements" }), _jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: progress.achievements.map((achievement, index) => (_jsx("div", { className: "p-4 bg-yellow-50 border border-yellow-200 rounded-lg", children: _jsxs("div", { className: "font-medium text-yellow-900", children: ["\uD83C\uDFC6 ", achievement] }) }, index))) })] })), (!progress?.achievements || progress.achievements.length === 0) && !loading && (_jsx("div", { className: "bg-white rounded-lg shadow-sm border border-gray-200 p-8", children: _jsx("p", { className: "text-gray-600", children: "No achievements yet. Start completing exercises to earn achievements!" }) }))] }));
};
export default Profile;
